/*
 * Seth James England
 * 09/05/18
 * CdCollectio.Java
 * this program is meant to list your cd collection
 */

package u3a4_cdcollection;
// importing the package util
import java.util.*;
/**
 * Seth James England
 */
public class U3A4_CdCollection extends javax.swing.JFrame {
    ArrayList <String> songsAndArtists = new ArrayList();
    /**
     * Creates new form U3A4_CdCollection
     */
    public U3A4_CdCollection() {
        initComponents();
        // the code declared globally in the beginning of the program that doesnt allow the buttons to be pressed until the program in initialize
        displayButton.setEnabled(false);
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        titleArtistLabel = new javax.swing.JLabel();
        enterText = new javax.swing.JTextField();
        displayButton = new javax.swing.JButton();
        initializeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        noticeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitButtonFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainLabel.setText("CD Collection");

        titleArtistLabel.setText("Title - Artist:");

        enterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTextActionPerformed(evt);
            }
        });

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        initializeButton.setText("Initialize");
        initializeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initializeButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        outputText.setEditable(false);
        outputText.setColumns(20);
        outputText.setLineWrap(true);
        outputText.setRows(5);
        outputText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(outputText);

        noticeLabel.setText("Be EXACT (capitals too) for remove button to work");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(mainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleArtistLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(displayButton)
                        .addGap(18, 18, 18)
                        .addComponent(initializeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(noticeLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleArtistLabel)
                    .addComponent(enterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayButton)
                    .addComponent(initializeButton)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addGap(1, 1, 1)
                .addComponent(noticeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        exitButtonFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitButtonFile.setText("Exit");
        exitButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonFileActionPerformed(evt);
            }
        });
        jMenu1.add(exitButtonFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTextActionPerformed
        
    }//GEN-LAST:event_enterTextActionPerformed
    /*
    * the display button prints out in the text area a list of the songs from newest added to oldest added, and in alphabetical order
    */
    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        //the for loop hat prints the songs in order from oldest added to newest added
        outputText.setText("Original Order:");
        for (int i = 0; i < songsAndArtists.size(); i++) {
            outputText.append("\n");
            outputText.append(songsAndArtists.get(i));
       }
        outputText.append("\n");
        outputText.append("\n");
        outputText.append("\n");
        outputText.append("Alphabetical Order:");
        Collections.sort(songsAndArtists);
        // the for loop that sorts the songs in alphabetical order
        for (int x = 0; x < songsAndArtists.size(); x++) {
        outputText.append("\n");
        outputText.append(songsAndArtists.get(x));
        }
    }//GEN-LAST:event_displayButtonActionPerformed
    /*
    *THE INITIALIZE BUTTON initializes the program, allowing oher buttons to be pushed, and setting a base 5 songs for the arraylist
    */
    private void initializeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initializeButtonActionPerformed
        // displays a set number of songs to begin with, plus it enables the other butons in the program
        Collections.addAll(songsAndArtists, "Catch and release by Matt Simons", "This is America by Childish Gambino", "Wait by the River by Lord Huron", "Gummy by BROCKHAMPTON", "Zipper by BROCKHAMPTON");
        displayButton.setEnabled(true);
        addButton.setEnabled(true);
        removeButton.setEnabled(true);
        initializeButton.setEnabled(false);
    }//GEN-LAST:event_initializeButtonActionPerformed
    /*
    * the add button allowsa new songs to be added to the arraylist
    */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // adds a song to the list 
        songsAndArtists.add(enterText.getText());
    }//GEN-LAST:event_addButtonActionPerformed
    /*
    REMOVES a specificed song and artist fromt he array list
    */
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // removes the specified song and artist from the list
        songsAndArtists.remove (enterText.getText());
    }//GEN-LAST:event_removeButtonActionPerformed
    /*
    * Exits the entire program
    */
    private void exitButtonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonFileActionPerformed
        // exits the program with ctrl E
        System.exit(0);
    }//GEN-LAST:event_exitButtonFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U3A4_CdCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U3A4_CdCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U3A4_CdCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U3A4_CdCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U3A4_CdCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextField enterText;
    private javax.swing.JMenuItem exitButtonFile;
    private javax.swing.JButton initializeButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel noticeLabel;
    private javax.swing.JTextArea outputText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel titleArtistLabel;
    // End of variables declaration//GEN-END:variables
}
